version: '2'
services:

  mysql:
    image: mysql:5.5
    container_name: locadoradb
    #command: --default-authentication-plugin=mysql_native_password
    volumes:
     - './sql:/docker-entrypoint-initdb.d'
    ports:
    - '3306:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    logging:
      driver: "none"
    networks:
      locadora-net:
        ipv4_address: 172.20.0.2

  locadora:
    image: node:8.12.0
    container_name: locadora
    ports:
      - 80:3000
      - 8080:8080
    restart: always
    working_dir: /app
    entrypoint: "/bin/sh -c 'npm install && npm run nodemon'"
    volumes:
      - ./../:/app
    networks:
      locadora-net:
        ipv4_address: 172.20.0.3
    depends_on:
      - mysql

networks:
  locadora-net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/24
        gateway: 172.20.0.1